#!/usr/bin/env bash
name="sane"
version="1.3.0"
url="sane"
description="ane"

source="https://download.gnome.org/sources/gsound/${version%.*}/gsound-${version}.tar.xz"
depends=""

group="media.libs"

setup(){
cd $SOURCEDIR
    meson setup $BUILDDIR \
		-Dgtk_doc=false \
		-Dintrospection=true \
		-Denable_vala=true \
		--buildtype=release \
		--prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    ninja -C $BUILDDIR $jobs
}

package(){
   DESTDIR=$DESTDIR ninja -C $BUILDDIR install $jobs
}

