#!/usr/bin/env bash
name="cjs"
version="6.0.0"
description="Javascript Bindings for Cinnamon"
source="https://github.com/linuxmint/cjs/archive/refs/tags/${version}.tar.gz"
depends="mozjs102"
builddepend="libiconv"
group="gnome.extra"


setup(){
	cd $SOURCEDIR
    meson setup $BUILDDIR --prefix=/usr \
        --libdir=/usr/lib64/ \
        --libexecdir=/usr/lib64 \
        --buildtype=plain \
        -Dinstalled_tests=false \
        -Ddtrace=false

}

build(){
    meson compile -C $BUILDDIR
}

package(){
    DESTDIR="$DESTDIR" meson install -C $BUILDDIR
}

