#!/usr/bin/env bash
name="nemo"
version="6.2.0"
description="File manager for the Cinnamon desktop environment"
source="https://github.com/linuxmint/nemo/archive/refs/tags/${version}.tar.gz"
depends="cinnamon-desktop,dconf,gvfs,libexif,libnotify,libxml2,python,xapp"
builddepend="meson,intltool,gobject-introspection,libgsf"
group="cinnamon.base"


setup () {
	cd $SOURCEDIR
	sed -i '/^\[Desktop Entry/,/^\[Desktop Action/ s/^Name\(.*\)=.*/Name\1=Nemo/' data/nemo.desktop.in
    meson setup $BUILDDIR --prefix=/usr \
 		--libdir=/usr/lib64/ \
 		--libexecdir=/usr/lib64/nemo/nemo-${version} \
		-Dxmp=true \
		-Dgtk_doc=false \
		-Dselinux=false
}

build(){
    meson compile -C $BUILDDIR
}

package(){
    DESTDIR="$DESTDIR" meson install -C $BUILDDIR
}
