#!/usr/bin/env bash
name="nemo"
version="6.0.2"
description="File manager for the Cinnamon desktop environment"
source="https://github.com/linuxmint/nemo/archive/refs/tags/${version}.tar.gz"
depends="cinnamon-desktop,dconf,gvfs,libexif,libgsf,libnotify,libxml2,python,xapp"
builddepend="meson,intltool,gobject-introspection,libabigail"
group="cinnamon.base"


setup () {
	cd $SOURCEDIR

    meson setup $BUILDDIR --prefix=/usr \
 		--libdir=/usr/lib64/ \
		-Dxmp=true \
		-Dgtk_doc=false \
		-Dselinux=false
}

build () {
    ninja -C $BUILDDIR
}

package () {
    DESTDIR=$DESTDIR ninja -C $BUILDDIR install
}
