#!/usr/bin/env bash
name="colord"
version="1.4.7"
description="System service to accurately color manage input and output devices "
source="https://github.com/hughsie/colord/archive/refs/tags/$version.tar.gz"
depends="lcms2,libgusb,libgudev,polkit,sqlite,shared-mime-info"
builddepend="bash-completion,docbook-xsl,git,gobject-introspection,gtk-doc,meson,vala"
group="x11.misc"


setup(){
	cp -prvf $PACKAGEDIR/colord-1.4.7-upstream_fixes-1.patch /tmp/bps/build/
	cd $SOURCEDIR
	patch -Np1 -i ../colord-1.4.7-upstream_fixes-1.patch
	
    meson setup $BUILDDIR --prefix=/usr \
        --libdir=/usr/lib64/ \
		-Dsystemd=false \
		-Dargyllcms_sensor=true \
		-Dman=false \
		-Ddocs=false \
		-Ddaemon_user=colord \
		-Dvapi=true \
		-Dtests=false \
		-Dinstalled_tests=false \
		-Dman=false \
		-Ddocs=false
}

build(){
    ninja -C $BUILDDIR
}

package(){
    DESTDIR=$DESTDIR ninja -C $BUILDDIR install
    
    groupadd -g 71 colord
	useradd -c "Color Daemon Owner" -d $DESTDIR/var/lib/colord -u 71 -g colord -s /bin/false colord
    chown -R colord:colord "$DESTDIR"/var/lib/colord
}

