#!/usr/bin/env bash
name="cinnamon-settings-daemon"
version="6.0.0"
description="The Cinnamon Settings daemon"
source="https://github.com/linuxmint/cinnamon-settings-daemon/archive/refs/tags/${version}.tar.gz"
depends="cinnamon-desktop,colord,dbus-glib,libcanberra,cups,libgnomekbd,libgudev,libnotify,librsvg,libwacom,nss,polkit,upower"
builddepend="meson,ninja,xf86-input-wacom"
group="cinnamon.base"


setup(){
	cd $SOURCEDIR
    meson setup $BUILDDIR --prefix=/usr \
        --libdir=/usr/lib64/ \
        --libexecdir=/usr/lib64/cinnamon-settings-daemon-6.0.0 \
        --buildtype=plain \
        -Duse_smartcard=disabled
}

build(){
    meson compile -C $BUILDDIR
}

package(){
    DESTDIR="$DESTDIR" meson install -C $BUILDDIR
}

