#!/usr/bin/env bash
name="liburcu"
version="0.14"
description="LGPLv2.1 userspace RCU (read-copy-update) library"
source="https://lttng.org/files/urcu/userspace-rcu-latest-$version.tar.bz2"
depends=""
builddepend=""
group="sys.libs"


setup(){
	cd $SOURCEDIR
	./configure --prefix=/usr \
        --libdir=/usr/lib64/ 
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

