#!/usr/bin/env bash
name="zenity"
version="3.44.1"
url="https://wiki.gnome.org/Projects/Zenity"
description="Display dialog boxes from the command line and shell scripts"
source="https://download.gnome.org/sources/zenity/${version%.*}/zenity-${version}.tar.xz"
depends="gtk3,libnotify"
makedepends="meson,yelp-tools"
group="gnome.extra"

setup(){
cd $SOURCEDIR
    meson setup $BUILDDIR \
        --prefix=/usr \
		    -Db_lto=true \
		    -Dlibnotify=true
}

build(){
    ninja -C  $BUILDDIR $jobs
}

package(){
 DESTDIR=$DESTDIR   ninja -C  $BUILDDIR install $jobs
}

